/* 유닛 번호 → 이름 ─────────────────────────────────────────────────────────────
 * OpenBW가 내는 트랙에는 유닛이 **번호**(units.dat 차례)로 들어 있다. 앱은 이름으로
 * 모델과 값 표를 찾으므로(bwUnits.ts) 여기서 옮긴다.
 *
 * scripts/fixtures/unit-ids.json 에서 뽑아 만든 표다. 손으로 고치지 마라 — 그 파일이 원장이다.
 * "Dark Templar (Unit)"처럼 참값 표기가 앱 표기와 다른 것은 여기서 이미 맞춰 두었다.
 */
export const BW_UNIT_NAME: Record<number, string> = {
  0: "Marine",
  1: "Ghost",
  2: "Vulture",
  3: "Goliath",
  4: "Goliath Turret",
  5: "Siege Tank (Tank Mode)",
  6: "Siege Tank Turret (Tank Mode)",
  7: "SCV",
  8: "Wraith",
  9: "Science Vessel",
  10: "Gui Montag (Firebat)",
  11: "Dropship",
  12: "Battlecruiser",
  13: "Spider Mine",
  14: "Nuclear Missile",
  15: "Civilian",
  16: "Sarah Kerrigan (Ghost)",
  17: "Alan Schezar (Goliath)",
  18: "Alan Schezar Turret",
  19: "Jim Raynor (Vulture)",
  20: "Jim Raynor (Marine)",
  21: "Tom Kazansky (Wraith)",
  22: "Magellan (Science Vessel)",
  23: "Edmund Duke (Tank Mode)",
  24: "Edmund Duke Turret (Tank Mode)",
  25: "Edmund Duke (Siege Mode)",
  26: "Edmund Duke Turret (Siege Mode)",
  27: "Arcturus Mengsk (Battlecruiser)",
  28: "Hyperion (Battlecruiser)",
  29: "Norad II (Battlecruiser)",
  30: "Siege Tank (Siege Mode)",
  31: "Siege Tank Turret (Siege Mode)",
  32: "Firebat",
  33: "Scanner Sweep",
  34: "Medic",
  35: "Larva",
  36: "Egg",
  37: "Zergling",
  38: "Hydralisk",
  39: "Ultralisk",
  40: "Broodling",
  41: "Drone",
  42: "Overlord",
  43: "Mutalisk",
  44: "Guardian",
  45: "Queen",
  46: "Defiler",
  47: "Scourge",
  48: "Torrasque (Ultralisk)",
  49: "Matriarch (Queen)",
  50: "Infested Terran",
  51: "Infested Kerrigan (Infested Terran)",
  52: "Unclean One (Defiler)",
  53: "Hunter Killer (Hydralisk)",
  54: "Devouring One (Zergling)",
  55: "Kukulza (Mutalisk)",
  56: "Kukulza (Guardian)",
  57: "Yggdrasill (Overlord)",
  58: "Valkyrie",
  59: "Mutalisk Cocoon",
  60: "Corsair",
  61: "Dark Templar",
  62: "Devourer",
  63: "Dark Archon",
  64: "Probe",
  65: "Zealot",
  66: "Dragoon",
  67: "High Templar",
  68: "Archon",
  69: "Shuttle",
  70: "Scout",
  71: "Arbiter",
  72: "Carrier",
  73: "Interceptor",
  74: "Dark Templar (Hero)",
  75: "Zeratul (Dark Templar)",
  76: "Tassadar/Zeratul (Archon)",
  77: "Fenix (Zealot)",
  78: "Fenix (Dragoon)",
  79: "Tassadar (Templar)",
  80: "Mojo (Scout)",
  81: "Warbringer (Reaver)",
  82: "Gantrithor (Carrier)",
  83: "Reaver",
  84: "Observer",
  85: "Scarab",
  86: "Danimoth (Arbiter)",
  87: "Aldaris (Templar)",
  88: "Artanis (Scout)",
  89: "Rhynadon (Badlands Critter)",
  90: "Bengalaas (Jungle Critter)",
  91: "Cargo Ship (Unused)",
  92: "Mercenary Gunship (Unused)",
  93: "Scantid (Desert Critter)",
  94: "Kakaru (Twilight Critter)",
  95: "Ragnasaur (Ashworld Critter)",
  96: "Ursadon (Ice World Critter)",
  97: "Lurker Egg",
  98: "Raszagal (Corsair)",
  99: "Samir Duran (Ghost)",
  100: "Alexei Stukov (Ghost)",
  101: "Map Revealer",
  102: "Gerard DuGalle (BattleCruiser)",
  103: "Lurker",
  104: "Infested Duran (Infested Terran)",
  105: "Disruption Web",
  106: "Command Center",
  107: "Comsat Station",
  108: "Nuclear Silo",
  109: "Supply Depot",
  110: "Refinery",
  111: "Barracks",
  112: "Academy",
  113: "Factory",
  114: "Starport",
  115: "Control Tower",
  116: "Science Facility",
  117: "Covert Ops",
  118: "Physics Lab",
  119: "Starbase (Unused)",
  120: "Machine Shop",
  121: "Repair Bay (Unused)",
  122: "Engineering Bay",
  123: "Armory",
  124: "Missile Turret",
  125: "Bunker",
  126: "Norad II (Crashed)",
  127: "Ion Cannon",
  128: "Uraj Crystal",
  129: "Khalis Crystal",
  130: "Infested Command Center",
  131: "Hatchery",
  132: "Lair",
  133: "Hive",
  134: "Nydus Canal",
  135: "Hydralisk Den",
  136: "Defiler Mound",
  137: "Greater Spire",
  138: "Queen's Nest",
  139: "Evolution Chamber",
  140: "Ultralisk Cavern",
  141: "Spire",
  142: "Spawning Pool",
  143: "Creep Colony",
  144: "Spore Colony",
  145: "Unused Zerg Building1",
  146: "Sunken Colony",
  147: "Overmind (With Shell)",
  148: "Overmind",
  149: "Extractor",
  150: "Mature Chrysalis",
  151: "Cerebrate",
  152: "Cerebrate Daggoth",
  153: "Unused Zerg Building2",
  154: "Nexus",
  155: "Robotics Facility",
  156: "Pylon",
  157: "Assimilator",
  158: "Unused Protoss Building1",
  159: "Observatory",
  160: "Gateway",
  161: "Unused Protoss Building2",
  162: "Photon Cannon",
  163: "Citadel of Adun",
  164: "Cybernetics Core",
  165: "Templar Archives",
  166: "Forge",
  167: "Stargate",
  168: "Stasis Cell/Prison",
  169: "Fleet Beacon",
  170: "Arbiter Tribunal",
  171: "Robotics Support Bay",
  172: "Shield Battery",
  173: "Khaydarin Crystal Formation",
  174: "Temple",
  175: "Xel'Naga Temple",
  176: "Mineral Field (Type 1)",
  177: "Mineral Field (Type 2)",
  178: "Mineral Field (Type 3)",
  179: "Cave (Unused)",
  180: "Cave-in (Unused)",
  181: "Cantina (Unused)",
  182: "Mining Platform (Unused)",
  183: "Independent Command Center (Unused)",
  184: "Independent Starport (Unused)",
  185: "Independent Jump Gate (Unused)",
  186: "Ruins (Unused)",
  187: "Khaydarin Crystal Formation (Unused)",
  188: "Vespene Geyser",
  189: "Warp Gate",
  190: "Psi Disrupter",
  191: "Marker",
  192: "Marker",
  193: "Marker",
  194: "Beacon",
  195: "Beacon",
  196: "Beacon",
  197: "Flag Beacon",
  198: "Flag Beacon",
  199: "Flag Beacon",
  200: "Power Generator",
  201: "Overmind Cocoon",
  202: "Dark Swarm",
  203: "Floor Missile Trap",
  204: "Floor Hatch (Unused)",
  205: "Left Upper Level Door",
  206: "Right Upper Level Door",
  207: "Left Pit Door",
  208: "Right Pit Door",
  209: "Floor Gun Trap",
  210: "Left Wall Missile Trap",
  211: "Left Wall Flame Trap",
  212: "Right Wall Missile Trap",
  213: "Right Wall Flame Trap",
  214: "Start Location",
  215: "Flag",
  216: "Young Chrysalis",
  217: "Psi Emitter",
  218: "Data Disc",
  219: "Khaydarin Crystal",
  220: "Mineral Cluster Type 1",
  221: "Mineral Cluster Type 2",
  222: "Vespene Gas Orb Type 1",
  223: "Vespene Gas Orb Type 2",
  224: "Vespene Gas Sac Type 1",
  225: "Vespene Gas Sac Type 2",
  226: "Vespene Gas Tank Type 1",
};

/** 지도가 놓아 준 자원 — 앱은 이것을 지도에서 그리므로 트랙에 없다(덤퍼가 이미 뺀다). */
export const MAP_RESOURCE_IDS = new Set([176, 177, 178, 188, 214]);
