/* 업그레이드·기술 이름표 — **만들어진 파일이다. 손으로 고치지 마라.**
 *
 * 만드는 법: tools/openbw/openbw/bwenums.h 의 UpgradeTypes·TechTypes 를 그대로 옮겼다.
 * 덤퍼는 이름 대신 번호를 낸다(글자를 90번 실어 보낼 이유가 없다) — 그 번호를
 * 사람이 읽는 이름으로 바꾸는 자가 여기다. 밑줄은 빈칸으로 폈다.
 */

/** 업그레이드 번호 → 이름. */
export const BW_UPGRADE_NAME: Record<number, string> = {
  0: "Terran Infantry Armor",
  1: "Terran Vehicle Plating",
  2: "Terran Ship Plating",
  3: "Zerg Carapace",
  4: "Zerg Flyer Carapace",
  5: "Protoss Ground Armor",
  6: "Protoss Air Armor",
  7: "Terran Infantry Weapons",
  8: "Terran Vehicle Weapons",
  9: "Terran Ship Weapons",
  10: "Zerg Melee Attacks",
  11: "Zerg Missile Attacks",
  12: "Zerg Flyer Attacks",
  13: "Protoss Ground Weapons",
  14: "Protoss Air Weapons",
  15: "Protoss Plasma Shields",
  16: "U 238 Shells",
  17: "Ion Thrusters",
  18: "unk 18",
  19: "Titan Reactor",
  20: "Ocular Implants",
  21: "Moebius Reactor",
  22: "Apollo Reactor",
  23: "Colossus Reactor",
  24: "Ventral Sacs",
  25: "Antennae",
  26: "Pneumatized Carapace",
  27: "Metabolic Boost",
  28: "Adrenal Glands",
  29: "Muscular Augments",
  30: "Grooved Spines",
  31: "Gamete Meiosis",
  32: "Metasynaptic Node",
  33: "Singularity Charge",
  34: "Leg Enhancements",
  35: "Scarab Damage",
  36: "Reaver Capacity",
  37: "Gravitic Drive",
  38: "Sensor Array",
  39: "Gravitic Boosters",
  40: "Khaydarin Amulet",
  41: "Apial Sensors",
  42: "Gravitic Thrusters",
  43: "Carrier Capacity",
  44: "Khaydarin Core",
  45: "unk 45",
  46: "unk 46",
  47: "Argus Jewel",
  48: "unk 48",
  49: "Argus Talisman",
  50: "unk 50",
  51: "Caduceus Reactor",
  52: "Chitinous Plating",
  53: "Anabolic Synthesis",
  54: "Charon Boosters",
};

/** 기술 번호 → 이름. 덤퍼는 이진에서 0x8000을 얹어 업그레이드와 갈라 놓는다. */
export const BW_TECH_NAME: Record<number, string> = {
  0: "Stim Packs",
  1: "Lockdown",
  2: "EMP Shockwave",
  3: "Spider Mines",
  4: "Scanner Sweep",
  5: "Tank Siege Mode",
  6: "Defensive Matrix",
  7: "Irradiate",
  8: "Yamato Gun",
  9: "Cloaking Field",
  10: "Personnel Cloaking",
  11: "Burrowing",
  12: "Infestation",
  13: "Spawn Broodlings",
  14: "Dark Swarm",
  15: "Plague",
  16: "Consume",
  17: "Ensnare",
  18: "Parasite",
  19: "Psionic Storm",
  20: "Hallucination",
  21: "Recall",
  22: "Stasis Field",
  23: "Archon Warp",
  24: "Restoration",
  25: "Disruption Web",
  26: "Unused 26",
  27: "Mind Control",
  28: "Dark Archon Meld",
  29: "Feedback",
  30: "Optical Flare",
  31: "Maelstrom",
  32: "Lurker Aspect",
  33: "Unused 33",
  34: "Healing",
};

/** 덤퍼가 낸 번호(기술은 0x8000이 얹혀 있다) → 이름. 모르면 빈 글자. */
export function bwUpgradeName(id: number): string {
  return (id & 0x8000 ? BW_TECH_NAME[id & 0x7fff] : BW_UPGRADE_NAME[id]) ?? "";
}
